### ISSUE TITLE
CI Issues

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfsd-ctl#191]
@dryajov Could you look at https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfsd-ctl/detail/PR-190/3/pipeline.  It appears to be about port sharing.  I can't test it, because the tests are disabled for windows.

**Comment by VictorBjelkholm** [comment]
@richardschneider tests should not be disabled for windows anymore. You don't see the following picture after navigating to that url of yours?

![image](https://user-images.githubusercontent.com/459764/35481152-50581e8c-041e-11e8-8a05-8cd6fbce8419.png)

**Comment by dryajov** [comment]
@richardschneider @VictorBjelkholm I'm investigating it, as it happens in other repos as well (ipfs/interop for one) - this started happening kinda suddenly, I didn't see that problem until recently.

**Comment by dryajov** [comment]
@VictorBjelkholm I see that we're installing and starting up IPFS on the workers now (https://github.com/ipfs/jenkins/blob/01bd125f79455165c6e843d91ebdce042d25a0b7/linux-workers/main.tf#L72..L75), which is whats causing the issues with the conflicting ports. Is there a reason we're doing it? I think that's going to break a lot of builds across many repos?

**Comment by VictorBjelkholm** [comment]
@dryajov yes, that is true. The distribution of caches and builds will happen via IPFS communication between workers and the master.

It should not cause any conflicts as the tests should not have any hardcoded ports in them.

**Comment by dryajov** [comment]
Thanks @VictorBjelkholm. I agree, we should not be using hardcoded ports and addresses anywhere unless justified. In the case of `ipfsd-ctl`, it only uses the default configs when spawning non `disposable` nodes with the default config, in which case it uses the respective `ipfs` defaults for each daemon type. This should not be a big issue and we should be able to provide alternative addrs for those tests so that they don't conflict with the running `ipfs` daemon.

**Comment by richardschneider** [comment]
@dryajov any progress? All `ipfsd-ctl` PRs are failing because of this.

**Comment by dryajov** [comment]
@richardschneider this has been addressed here - https://github.com/ipfs/js-ipfsd-ctl/pull/196

**Comment by richardschneider** [comment]
@dryajov needs to be merged!
