### ISSUE TITLE
IPFS_EXEC is not documented anymore

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfsd-ctl#216]
it was in the readme at some point, really useful

**Comment by VictorBjelkholm** [comment]
I just hit this as well. Apparently, since we're spawning both js-ipfs and go-ipfs nodes and they both would be candidates for `IPFS_EXEC`, if you're using both, it becomes messed up. So the `IPFS_EXEC` support has been removed completely.

So with that, I propose the following changes:

- add `IPFS_JS_EXEC` and `IPFS_GO_EXEC` env vars for respective binary for the implementations. Extremely useful env var when doing testing.
- add warning if `IPFS_EXEC` env var is not empty, that states that `IPFS_EXEC` does no longer do anything and `IPFS_JS_EXEC` and `IPFS_GO_EXEC` is needed instead.

**Comment by dryajov** [comment]
Yes we should add it to the readme - however there are a few caveats. 

Since we added different executable types - `go`, `js` and `proc`, there could be cases when setting the variable with an incompatible executable would fail, also starting more than one daemon with different `exec` types will fail if the env variable is not updated accordingly between runs. 

We need to introduce an env variable for each daemon type (suggested by @VictorBjelkholm on IRC) - IPFS_GO_EXEC and IPFS_JS_EXEC.

**Comment by dryajov** [comment]
ah, @VictorBjelkholm beat me to it :)

**Comment by diasdavid** [comment]
Done with #219
