### ISSUE TITLE
Non-disposable Daemon fails to initialize from custom repo

### ISSUE THREAD

**Issue by bizimUfuk** [ipfs/js-ipfsd-ctl#229]
Hello,
Maybe a noob question, but I cannot find a way out.
I am trying to spawn a non-disposable daemon with a custom repo in VM environment (Ubuntu 16.04, Node 9.11.1)

Test code is as following:
```const IPFSFactory = require('ipfsd-ctl')
const f = IPFSFactory.create({type: 'proc', exec: require('ipfs') })

f.spawn({ disposable: false , repoPath: "./.ipfsdctlrepo"},(err, ipfsd) => {
  if (err) { throw err }
    ipfsd.init((_) => {
      ipfsd.start((_) => {
        ipfsd.api.id((_, id) => {
          if (err) {            throw err          }
          console.log('alice')
          console.log(id)
          ipfsd.stop()
        })
      })
    })
})
```
When I run it, the `./.ipfsdctlrepo` folder is created and code exits properly. But if repo is already created, it fails with error:
> Not able to init from state: stopped

I located the issue to the file named "version" in the repo. If I delete this file manually, then it initializes with no error, but again creates this file.

I just tried on Heroku (node 8.9.1), and works with no error. Does it have anything to do with the Node v9.11.1 or VM/Ubuntu issue?

**Comment by dryajov** [comment]
`ipfsd.init` assumes that there is no prior repo, that's why it fails. Your logic should account for that and be to detect if the repo is already created, I would simply let `ipfsd.init` fail if the repo exists and continue with `ipfsd.start` (after making sure I get the appropriate error message). There are some good examples in https://github.com/ipfs-shipyard/ipfs-desktop/blob/6a56921ca2e30389d33e6c58113b323a781c0e65/src/index.js on how to go about non-disposable repos.

I'll add a non-disposable example to the `examples` directory to illustrate how to go about it as well.

**Comment by vasco-santos** [comment]
@dryajov @bizimUfuk I created a new issue for the non-disposable node example. 

This way, I can close this issue, since it seems solved.
